### ISSUE TITLE
[REQ] Add variable {MAXPING}

### ISSUE THREAD

**Issue by crashzk** [connercsbn/HighPingKicker#1]
It would be interesting to add the **`{MAXPING}`** variable, it will show the maximum ping that was configured in the plugin.

Example of use:
```
"kick_message": "{NAME} was kicked due to ping limit. (Ping: {PING} | Max: {MAXPING})",
"warning_message": "You will be kicked due to ping limit! You have {WARN} of {MAXWARN} warnings. Maximum ping allowed {MAXPING}",
```

**Comment by connercsbn** [comment]
Good idea! Added in v0.0.5 (commit 9f9d1bde82c18f024c42c4ef9888d4e18471f466)
